Adds support to collect the out of ceph commands
ashishranjan738/must-gather pull request #7
Opened 2019-07-16 13:06 UTC by ashishranjan738

Signed-off-by: Ashish Ranjan <aranjan@redhat.com>

This commit adds support for collecting the output of `ceph commands`.The output of commands that are getting collected are given below:
```
ceph status
ceph health detail
ceph osd tree
ceph osd stat
ceph osd dump
ceph mon stat
ceph mon dump
ceph df
ceph report
ceph osd df tree
ceph fs dump --format json-pretty
ceph fs ls
ceph pg dump
ceph health detail --format json-pretty
ceph osd crush show-tunables
```

2019-07-17 08:04 UTC, leseb requested changes

2019-07-17 08:04 UTC, leseb commented on collection-scripts/gather_ceph_resources
> +ceph_commands=()
Please add:

* `ceph osd crush dump`
* `ceph mgr dump`
* `ceph mds stat`
* `ceph versions`

2019-07-18 04:07 UTC, ashishranjan738 commented on collection-scripts/gather_ceph_resources
> +ceph_commands=()
yup added

2019-07-18 04:09 UTC, merged

2019-07-18 10:37 UTC, ashishkumsingh commented
Hey @ashishranjan738, instead of writing all commands output to a single file, can we create separate files for commands inside a common directory?